## Упражнение 00: Загрузка и сохранение

Exercise 00

Load and save

Turn-in directory : ex00/

Files to turn in : load_and_save.ipynb

Allowed functions : import pandas as pd

Congratulations! Five days and one rush are behind you. They were dedicated to
building good fundamental skills in working with Python. Now you know all the basic
data types, useful built-in functions, how to work with a virtual environment, how to use
OOP, how to use logging, how to parse data from websites, and how to send messages in
a Slack channel. In the following week, we will be more focused on data science. It will
be a week full of Pandas exercises. Pandas is one of the most popular and useful libraries
in the field. You will love it too!

In this exercise, you will need to load the [log file](https://drive.google.com/file/d/1kgByP3EZHL8xAm-oGaBpf0-fPdVIYRaY/view) (put it in the directory `data` in the
src directory of the day) into a dataframe, change the delimiter, and save it to another
file.

The task is:

* `read_csv`:
  * filter the rows with index 2 and 3 using the argument skiprows, we know that
  these observations were fake
  * filter the last 2 rows from the footer using the argument skipfooter, we know
  that these observations were fake too
  * assign the following names to the column: `datetime`, `user`
  * use datetime as the index column
* rename `datetime` to `date_time`
* to_csv:
  * use `’;’` as the delimiter
  * save it to a file with the name `feed-views-semicolon.log`

As the result of `read_csv`, you need to achieve the following:

```
In [3]: df.head()
Out[3]:
user
datetime
2020-04-17 12:01:08.463179 artem
2020-04-17 12:01:23.743946 artem
2020-04-17 12:35:52.735016 artem
2020-04-17 12:36:21.401412 oksana
2020-04-17 12:36:22.023355 oksana

In [4]: df.tail()
Out[4]:
user
datetime
2020-05-21 16:36:40.915488 ekaterina
2020-05-21 17:49:36.429237 maxim
2020-05-21 18:45:20.441142 valentina
2020-05-21 23:03:06.457819 maxim
2020-05-21 23:23:49.995349 pavel
```

Think about how many lines of code you would have needed to write if you had had
to do it without Pandas

In [4]:
import pandas as pd

In [5]:
file_path = 'data/feed-views.log'
df = pd.read_csv(file_path, sep='\t', skiprows=[2, 3], skipfooter=2, names=['datetime', 'user'], index_col='datetime')
df.index.name = 'date_time'

/tmp/ipython-input-5-1540292205.py:2: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.
  df = pd.read_csv(file_path, sep='\t', skiprows=[2, 3], skipfooter=2, names=['datetime', 'user'], index_col='datetime')

In [6]:
df.head()

                              user
date_time
2020-04-17 12:01:08.463179   artem
2020-04-17 12:01:23.743946   artem
2020-04-17 12:35:52.735016   artem
2020-04-17 12:36:21.401412  oksana
2020-04-17 12:36:22.023355  oksana

In [7]:
df.tail()

                                 user
date_time
2020-05-21 16:36:40.915488  ekaterina
2020-05-21 17:49:36.429237      maxim
2020-05-21 18:45:20.441142  valentina
2020-05-21 23:03:06.457819      maxim
2020-05-21 23:23:49.995349      pavel

In [8]:
df.to_csv(sep=';', path_or_buf='data/feed-views-semicolon.log')

In [9]:
df_csv = pd.read_csv("data/feed-views-semicolon.log", sep=';')

In [10]:
df_csv.head()

                    date_time    user
0  2020-04-17 12:01:08.463179   artem
1  2020-04-17 12:01:23.743946   artem
2  2020-04-17 12:35:52.735016   artem
3  2020-04-17 12:36:21.401412  oksana
4  2020-04-17 12:36:22.023355  oksana

In [11]:
df_csv.tail()

                       date_time       user
1067  2020-05-21 16:36:40.915488  ekaterina
1068  2020-05-21 17:49:36.429237      maxim
1069  2020-05-21 18:45:20.441142  valentina
1070  2020-05-21 23:03:06.457819      maxim
1071  2020-05-21 23:23:49.995349      pavel

## Упражнение 01: Основные операции

Exercise 01

Basic operations

Turn-in directory : ex01/

Files to turn in : basic_operations.ipynb

Allowed functions : import pandas as pd

We are confident that you understand that this is not everything that Pandas can do
for you. Let us go deeper and wider.

In this exercise, you will work with a single log of users who visited a page, including
their timestamps.

* create a dataframe `views` with two columns: `datetime` and `user` by reading `feed-views.log`
  * convert the `datetime` to the `datetime64[ns]` `Dtype`
  * extract the year, month, day, hour, minute, and second from the values of that
  column to the new columns
* create the new column `daytime`
  * you need to assign the particular time of day value if an hour is within a
  particular interval, for example, afternoon if the hour is larger than `11` and
  less or equal to `17`
  * 0 – 3.59 `night`, 4 – 6.59 `early morning`, 7 – 10.59 `morning`, 11 – 16.59 `afternoon`, 17 – 19.59 `early evening`, 20 – 23.59 `evening`
  * use the method `cut` to solve this subtask
  * assign the column `user` as the index
* calculate the number of elements in your dataframe
  * use the method `count()`
  * calculate the number of elements in each time of day category using the method
  `value_counts()`
* sort values in your dataframe by hour, minute, and second in ascending order
  (simultaneously and not one by one)
* calculate the minimum and maximum for the hours and the mode for the daytime
  categories
  * calculate the maximum of hour for the rows where the time of day is night
  * calculate the minimum of hour for the rows where the time of day is morning
  * In addition to this, find out who visited the page at those hours (make one
  example from that)
  * calculate the mode for the hour and daytime
* show the 3 earliest hours in the morning and the corresponding usernames and the
  3 latest hours and the usernames using `nsmallest()` and `nlargest()`
* use the method `describe()` to get the basic statistics for the columns
  * to find out what the most popular interval for visiting the page is, calculate
    the interquartile range for the hour by extracting values from the result of the
`describe()` method and store it in the variable `iqr`

In [12]:
import pandas as pd

In [13]:
file_path = 'data/feed-views.log'
views = pd.read_csv(file_path, sep='\t', names=['datetime', 'user'])

views['datetime'] = pd.to_datetime(views['datetime'])

year = views['datetime'].dt.year
month = views['datetime'].dt.month
day = views['datetime'].dt.day
hour = views['datetime'].dt.hour
minute = views['datetime'].dt.minute
second = views['datetime'].dt.second

In [14]:
def get_daytime(hour):
    if (hour >= 0) & (hour <= 3.59):
        return 'night'
    elif (hour >= 4.) & (hour <= 6.59):
        return 'early morning'
    elif (hour >= 7.) & (hour <= 10.59):
        return 'morning'
    elif (hour >= 11.) & (hour <= 16.59):
        return 'afternoon'
    elif (hour >= 17.) & (hour <= 19.59):
        return 'early evening'
    elif (hour >= 20.) & (hour <= 23.59):
        return 'evening'
    else:
        return 'unknown'

views['daytime'] = views['datetime'].dt.hour.apply(get_daytime)

print(views.count())

print(views.value_counts('daytime'))

datetime    1076
user        1076
daytime     1076
dtype: int64
daytime
evening          509
afternoon        252
early evening    145
night            129
morning           36
early morning      5
Name: count, dtype: int64

In [15]:
views.sort_values(by='datetime', key=lambda x: x.dt.hour * 60 * 60 + x.dt.minute * 60 + x.dt.second, ascending=True, inplace=True)

In [16]:
views

                       datetime       user  daytime
944  2020-05-15 00:00:13.222265  valentina    night
945  2020-05-15 00:01:05.153738  valentina    night
563  2020-05-12 00:01:27.764025      pavel    night
564  2020-05-12 00:01:38.444917      pavel    night
565  2020-05-12 00:01:55.395042      pavel    night
...                         ...        ...      ...
1074 2020-05-21 23:49:22.386789      artem  evening
246  2020-05-09 23:53:55.599821   anatoliy  evening
247  2020-05-09 23:54:54.260791      pavel  evening
942  2020-05-14 23:58:56.754866  valentina  evening
943  2020-05-14 23:59:38.758438  alexander  evening

[1076 rows x 3 columns]

## Упражнение 02: Предварительная обработка

Exercise 02

Preprocessing

Turn-in directory : ex02/

Files to turn in : preprocessing.ipynb

Allowed functions : import pandas as pd

One day you will train machine learning models (no later than this week), but most
of them require the data to be clean and enriched: without duplicates or missing values.
Pandas is a great tool to do this. It gives you the tools not only to perform descriptive
analysis and understand your data better but to preprocess it too. That is what you are
going to do in this exercise.

* [download](https://drive.google.com/open?id=1kFMUiXtrlw5B6WTjJ-mUm4-STV28Zsvn) and read the CSV file and make `ID` the index column
* count the number of observations using the method `count()`
* drop the duplicates, taking into account only the following columns: `CarNumber`,
`Make_n_model`, `Fines`
  * between the two equal observations, you need to choose the last
  * check the number of observations again
* work with missing values
  * check how many values are missing from each column
  * drop all the columns with over 500 missing values using the argument `thresh`,
  check how many missing values are in each column
  * replace all the missing values in the `Refund` column with the previous value in
  that column for that cell, use the argument method, check how many values
  are missing from each column
  * replace all the missing values in the `Fines` column with the mean value of this
  column (exclude NA/null values when computing the mean value), check how
  many values are missing from each column
* split and parse the make and model
  * use the method apply both for splitting and for extracting the values to the
  new columns `Make` and `Model`
  * drop the column `Make_n_model`
  * save the dataframe in the JSON file auto.json in the format below:

    ```
    [{"CarNumber":"Y163O8161RUS","Refund":2.0,"Fines":3200.0,"Make":"Ford",
    "Model":"Focus"},
    {"CarNumber":"E432XX77RUS","Refund":1.0,"Fines":6500.0,"Make":"Toyota",
    "Model":"Camry"}]
    ```

In [17]:
from enum import auto
file_path = 'data/auto.csv'
auto_df = pd.read_csv(file_path, index_col='ID')
auto_df

        CarNumber    Make_n_model  Refund    Fines  History
ID
0    Y163O8161RUS      Ford Focus     2.0   3200.0      NaN
1     E432XX77RUS    Toyota Camry     1.0   6500.0      NaN
2     7184TT36RUS      Ford Focus     1.0   2100.0      NaN
3    X582HE161RUS      Ford Focus     2.0   2000.0      NaN
4    E34877152RUS      Ford Focus     2.0   6100.0      NaN
..            ...             ...     ...      ...      ...
926  Y163O8161RUS      Ford Focus     2.0   1600.0      NaN
927  M0309X197RUS      Ford Focus     1.0  22300.0      NaN
928  O673E8197RUS      Ford Focus     2.0    600.0      NaN
929  8610T8154RUS      Ford Focus     1.0   2000.0      NaN
930  H419XE197RUS  Toyota Corolla     2.0      NaN      2.0

[931 rows x 5 columns]

In [18]:
auto_df.count()

CarNumber       931
Make_n_model    931
Refund          914
Fines           869
History          82
dtype: int64

In [19]:
auto_df.drop_duplicates(['CarNumber', 'Make_n_model', 'Fines'], keep='last', inplace=True)
auto_df.count()

CarNumber       725
Make_n_model    725
Refund          713
Fines           665
History          65
dtype: int64

In [20]:
auto_df.isnull().sum()

CarNumber         0
Make_n_model      0
Refund           12
Fines            60
History         660
dtype: int64

In [21]:
auto_df = auto_df.dropna(axis=1, thresh=len(auto_df) - 500)

In [22]:
auto_df.count()

CarNumber       725
Make_n_model    725
Refund          713
Fines           665
dtype: int64

In [23]:
auto_df.loc[:, 'Refund'] = auto_df['Refund'].ffill()
auto_df.loc[:, 'Fines'] = auto_df['Fines'].fillna(auto_df['Fines'].mean())
auto_df.count()

CarNumber       725
Make_n_model    725
Refund          725
Fines           725
dtype: int64

In [24]:
# auto_df['Make'] = auto_df['Make_n_model'].apply(lambda x: x.split()[0])
# auto_df['Model'] = auto_df['Make_n_model'].apply(lambda x: x.split()[-1])

auto_df[['Make', 'Model']] = auto_df['Make_n_model'].str.split(n=1, expand=True)
auto_df.drop('Make_n_model', axis=1, inplace=True)

In [25]:
auto_df.to_json(path_or_buf='data/auto.json', orient='records', indent=4)

## Упражнение 03: Выборки и агрегации

Exercise 03

Selects and aggregations

Turn-in directory : ex03/

Files to turn in : selects_n_aggs.ipynb

Allowed functions : import pandas as pd

Ok, great. Now we have cleaned our data: all the duplicates have been dropped, all
the missing values have been deleted, and our columns have been reorganized to be more
convenient for analysis. Now we can go further. We have a lot of questions that need to
be answered.

* load the JSON file that you created in the previous exercise into a dataframe
  * set `CarNumber` as the index column
* make the following selects
  * display the rows only where the `fines` are more than `2,100`
  * display the rows only where the `fines` are more than `2,100` and the `refund`
  equals `2`
  * display the rows only where the `models` are from the list: `````[’Focus’, ’Corolla’]`````
  * display the rows only where the car number is from the list:
  ```[’Y7689C197RUS’, ’92928M178RUS’, ’7788KT197RUS’, ’H115YO163RUS’, ’X758HY197RUS’]```
* make the aggregations with the make and the model
  * display the median `fines` grouped by the `make`
  * display the median `fines` grouped by the `make` and the `model`
  * display the number of `fines` grouped by the `make` and the `model` in order to
  understand if we can trust the median values
  * display the minimum and the maximum `fines` grouped by the `make` and the
  `model` in order to better understand the variance
  * display the standard deviation of the `fines` grouped by the `make` and the `model`
  in order to better understand the variance
* make the aggregations with the car number
  * display the car numbers grouped by the number of the `fines` in descending
  order, we want to find those who most often violated the law
  * select from the initial dataframe all the rows corresponding to the top-1 car
  number, we want to zoom in a little bit
  * display the car numbers grouped by the sum of the `fines` in descending order,
  we want to find those who paid the most
  * select from the initial dataframe all the rows corresponding to the top-1 car
  number, we want to zoom in a little bit
  * display a table that answers the question: are there any car numbers that were connected to different models?

In [26]:
file_path = 'data/auto.json'
df = pd.read_json(file_path, orient='records')
df.set_index('CarNumber', inplace=True)

In [27]:
print(df[df['Fines'] > 2100])
print(df[(df['Fines'] > 2100) & (df['Refund'] == 2)])
print(df[df['Model'].isin(['Focus', 'Corolla'])])
print(df[df.index.isin(['Y7689C197RUS', '92928M178RUS', '7788KT197RUS', 'H115YO163RUS', 'X758HY197RUS'])])

              Refund         Fines        Make    Model
CarNumber
Y163O8161RUS       2   3200.000000        Ford    Focus
E432XX77RUS        1   6500.000000      Toyota    Camry
92918M178RUS       1   5700.000000        Ford    Focus
H234YH197RUS       2   6000.000000        Ford    Focus
E40577152RUS       1   8594.586466        Ford    Focus
...              ...           ...         ...      ...
O718MM163RUS       2   8594.586466        Ford    Focus
7065C8197RUS       2  11400.000000  Volkswagen   Passat
O22097197RUS       1  24300.000000        Ford    Focus
M0309X197RUS       1  22300.000000        Ford    Focus
H419XE197RUS       2   8594.586466      Toyota  Corolla

[455 rows x 4 columns]
              Refund         Fines        Make    Model
CarNumber
Y163O8161RUS       2   3200.000000        Ford    Focus
H234YH197RUS       2   6000.000000        Ford    Focus
707987163RUS       2   2200.000000        Ford    Focus
K330T8197RUS       2   8200.000000       Skoda  Octavia
M592CH197RUS       2   8594.586466       Skoda  Octavia
...              ...           ...         ...      ...
O136HO197RUS       2   7800.000000      Toyota  Corolla
O68897197RUS       2  12300.000000        Ford    Focus
O718MM163RUS       2   8594.586466        Ford    Focus
7065C8197RUS       2  11400.000000  Volkswagen   Passat
H419XE197RUS       2   8594.586466      Toyota  Corolla

[309 rows x 4 columns]
              Refund         Fines    Make    Model
CarNumber
Y163O8161RUS       2   3200.000000    Ford    Focus
7184TT36RUS        1   2100.000000    Ford    Focus
X582HE161RUS       2   2000.000000    Ford    Focus
92918M178RUS       1   5700.000000    Ford    Focus
H234YH197RUS       2   6000.000000    Ford    Focus
...              ...           ...     ...      ...
Y163O8161RUS       2   1600.000000    Ford    Focus
M0309X197RUS       1  22300.000000    Ford    Focus
O673E8197RUS       2    600.000000    Ford    Focus
8610T8154RUS       1   2000.000000    Ford    Focus
H419XE197RUS       2   8594.586466  Toyota  Corolla

[593 rows x 4 columns]
              Refund          Fines  Make  Model
CarNumber
92928M178RUS       1    8594.586466  Ford  Focus
H115YO163RUS       1    2200.000000  Ford  Focus
7788KT197RUS       2   12000.000000  Ford  Focus
X758HY197RUS       2   24200.000000  Ford  Focus
X758HY197RUS       2   72600.000000  Ford  Focus
Y7689C197RUS       1   27000.000000  Ford  Focus
92928M178RUS       1     600.000000  Ford  Focus
H115YO163RUS       1    8594.586466  Ford  Focus
H115YO163RUS       2    1100.000000  Ford  Focus
7788KT197RUS       2    8594.586466  Ford  Focus
7788KT197RUS       1   20000.000000  Ford  Focus
X758HY197RUS       2  145200.000000  Ford  Focus
92928M178RUS       1    1200.000000  Ford  Focus
Y7689C197RUS       2    9000.000000  Ford  Focus
Y7689C197RUS       2   45000.000000  Ford  Focus
7788KT197RUS       2    4000.000000  Ford  Focus
Y7689C197RUS       1   36000.000000  Ford  Focus
92928M178RUS       2    3000.000000  Ford  Focus

In [28]:
print(df.groupby('Make')['Fines'].median())
print(df.groupby(['Make', 'Model'])['Fines'].median())
print(df.groupby(['Make', 'Model'])['Fines'].count())
print(df.groupby(['Make', 'Model'])['Fines'].min(), df.groupby(['Make', 'Model'])['Fines'].max())
print(df.groupby(['Make', 'Model'])['Fines'].std())

Make
Audi          4200.0
BMW           6500.0
Ford          3500.0
Skoda         3250.0
Toyota        7700.0
Volkswagen    4300.0
Volvo         8500.0
Name: Fines, dtype: float64
Make        Model
Ford        Focus      3500.0
            Mondeo     7650.0
Skoda       Octavia    3250.0
Toyota      Camry      7700.0
            Corolla    7700.0
Volkswagen  Golf       4800.0
            Jetta      2800.0
            Passat     3500.0
            Touareg    5800.0
Name: Fines, dtype: float64
Make        Model
Ford        Focus      575
            Mondeo       6
Skoda       Octavia     48
Toyota      Camry       16
            Corolla     18
Volkswagen  Golf        20
            Jetta        6
            Passat      22
            Touareg      5
Name: Fines, dtype: int64
Make        Model
Ford        Focus       100.0
            Mondeo     1100.0
Skoda       Octavia     300.0
Toyota      Camry       500.0
            Corolla     900.0
Volkswagen  Golf        200.0
            Jetta       500.0
            Passat      100.0
            Touareg     500.0
Name: Fines, dtype: float64 Make        Model
Ford        Focus      180000.000000
            Mondeo      46200.000000
Skoda       Octavia    145000.000000
Toyota      Camry       22400.000000
            Corolla     34300.000000
Volkswagen  Golf       168000.000000
            Jetta       46000.000000
            Passat      29700.000000
            Touareg      8594.586466
Name: Fines, dtype: float64
Make        Model
Ford        Focus      15041.269437
            Mondeo     18987.329108
Skoda       Octavia    24339.742174
Toyota      Camry       6410.250654
            Corolla     9629.325617
Volkswagen  Golf       36950.839950
            Jetta      17743.026799
            Passat      6969.739135
            Touareg     3461.778173
Name: Fines, dtype: float64

In [29]:
afc = df.groupby(df.index)['Fines'].count().sort_values(ascending=False)
print(afc)
print(df.loc[afc.index[0]])
afs = df.groupby(df.index)['Fines'].sum().sort_values(ascending=False)
print(afs)
print(df.loc[afs.index[0]])
adm = df.groupby(df.index)['Model'].nunique()
print('Нет ни одного номера автомобилей, которые были связаны с разными моделями' if len(df.loc[adm[adm > 1].index]) == 0 else f'Есть номера автомобилей: {df.loc[adm[adm > 1].index]}')

CarNumber
Y7689C197RUS    4
7788KT197RUS    4
92928M178RUS    4
Y7129Y50RUS     3
X758HY197RUS    3
               ..
Y967O8197RUS    1
Y965O8197RUS    1
Y965EE197RUS    1
Y964O8197RUS    1
Y964EE197RUS    1
Name: Fines, Length: 531, dtype: int64
              Refund    Fines  Make  Model
CarNumber
Y7689C197RUS       1  27000.0  Ford  Focus
Y7689C197RUS       2   9000.0  Ford  Focus
Y7689C197RUS       2  45000.0  Ford  Focus
Y7689C197RUS       1  36000.0  Ford  Focus
CarNumber
X758HY197RUS    242000.0
9020YC197RUS    217500.0
M0279X197RUS    216000.0
Y352O8197RUS    207200.0
Y778EE197RUS    192000.0
                  ...
Y166O8161RUS       100.0
K326T8197RUS       100.0
Y195O8161RUS       100.0
C58078163RUS       100.0
705787163RUS       100.0
Name: Fines, Length: 531, dtype: float64
              Refund     Fines  Make  Model
CarNumber
X758HY197RUS       2   24200.0  Ford  Focus
X758HY197RUS       2   72600.0  Ford  Focus
X758HY197RUS       2  145200.0  Ford  Focus
Нет ни одного номера автомобилей, которые были связаны с разными моделями

In [30]:
# Оформление
print("Median fines by Make:")
display(df.groupby('Make')['Fines'].median())

print("Median fines by Make and Model:")
display(df.groupby(['Make', 'Model'])['Fines'].median())

print("Count of fines by Make and Model:")
display(df.groupby(['Make', 'Model'])['Fines'].count())

print("Minimum fines by Make and Model:")
display(df.groupby(['Make', 'Model'])['Fines'].min())

print("Maximum fines by Make and Model:")
display(df.groupby(['Make', 'Model'])['Fines'].max())

print("Standard deviation of fines by Make and Model:")
display(df.groupby(['Make', 'Model'])['Fines'].std())

Median fines by Make:

Make
Audi          4200.0
BMW           6500.0
Ford          3500.0
Skoda         3250.0
Toyota        7700.0
Volkswagen    4300.0
Volvo         8500.0
Name: Fines, dtype: float64

Median fines by Make and Model:

Make        Model
Ford        Focus      3500.0
            Mondeo     7650.0
Skoda       Octavia    3250.0
Toyota      Camry      7700.0
            Corolla    7700.0
Volkswagen  Golf       4800.0
            Jetta      2800.0
            Passat     3500.0
            Touareg    5800.0
Name: Fines, dtype: float64

Count of fines by Make and Model:

Make        Model
Ford        Focus      575
            Mondeo       6
Skoda       Octavia     48
Toyota      Camry       16
            Corolla     18
Volkswagen  Golf        20
            Jetta        6
            Passat      22
            Touareg      5
Name: Fines, dtype: int64

Minimum fines by Make and Model:

Make        Model
Ford        Focus       100.0
            Mondeo     1100.0
Skoda       Octavia     300.0
Toyota      Camry       500.0
            Corolla     900.0
Volkswagen  Golf        200.0
            Jetta       500.0
            Passat      100.0
            Touareg     500.0
Name: Fines, dtype: float64

Maximum fines by Make and Model:

Make        Model
Ford        Focus      180000.000000
            Mondeo      46200.000000
Skoda       Octavia    145000.000000
Toyota      Camry       22400.000000
            Corolla     34300.000000
Volkswagen  Golf       168000.000000
            Jetta       46000.000000
            Passat      29700.000000
            Touareg      8594.586466
Name: Fines, dtype: float64

Standard deviation of fines by Make and Model:

Make        Model
Ford        Focus      15041.269437
            Mondeo     18987.329108
Skoda       Octavia    24339.742174
Toyota      Camry       6410.250654
            Corolla     9629.325617
Volkswagen  Golf       36950.839950
            Jetta      17743.026799
            Passat      6969.739135
            Touareg     3461.778173
Name: Fines, dtype: float64

## Упражнение 04: Обогащение и преобразования

Exercise 04

Enrichment and transformations

Turn-in directory : ex04/

Files to turn in : enrichment.ipynb

Allowed functions : import pandas as pd, import numpy as np, import requests

Cool. But the more data you have the better the analysis you can conduct. Let us
enrich our initial dataset.

* read the JSON file that you saved in `ex02`

  * one of the columns has the float type, so let us define the format of it in
  pandas using `pd.options.display.float_format`: floats should be displayed with
  two decimals
  * there are values missing from the Model, do not do anything with them
* enrich the dataframe using a sample from that dataframe
  * create a sample with 200 new observations with `random_state = 21`
    * the sample should not have new combinations of the `car number`,
    `make` and `model`, so the whole dataset will be consistent in these terms
    * there are no restrictions on the `refund` and `fines`, you can take
    any value
    from these columns at random and use it towards any car number
  * concatenate the sample with the initial dataframe to a new dataframe `concat_rows`
* enrich the dataframe `concat_rows` by a new column with the data generated
  * create a series with the name `Year` using random integers from `1980` to `2019`
  * use `np.random.seed(21)` before generating the years
  * concatenate the series with the dataframe and name it `fines`
* enrich the dataframe with the data from another dataframe
  * create a new dataframe with the car numbers and their owners
      * get the most popular surnames (**you can find the file [surname.json](datasets/surname.json) in the attachments**) in the US
      * create a new series with the surnames (they should not have
      special characters like commas, brackets, etc.) from the data you gathered, the count
      should be equal to the number of unique car numbers using the sample
      (use `random_state = 21`)
      * create the dataframe owners with 2 columns: `CarNumber` and
`SURNAME`
  * append 5 more observations to the fines dataframe (come up with your own
ideas of CarNumber, etc.)
  * delete the dataframe last `20` observations from the owners and add 3 new
observations (they are not the same as those you add to the `fines` dataframe)
  * join both dataframes:
    * the new dataframe should have **only** the car numbers that exist in **both** dataframes
    * the new dataframe should have **all** the car numbers that exist in **both** dataframes
    * the new dataframe should have only the car numbers from the `fines` dataframe
    * the new dataframe should have only the car numbers from the `owners` dataframe
* create a pivot table from the `fines` dataframe, it should look like this (the values are
the sums of the fines), but with all the years (the values may be different for you):

    ![pivot-table](misc/images/pivot-table.png)

* save both the `fines` and `owners` dataframes to CSV files without an index

In [31]:
import pandas as pd
import numpy as np
import requests

In [32]:
file_path = 'data/auto.json'
autos = pd.read_json(file_path, orient='records')
print(autos.count())
autos.head()

CarNumber    725
Refund       725
Fines        725
Make         725
Model        716
dtype: int64

      CarNumber  Refund   Fines    Make  Model
0  Y163O8161RUS       2  3200.0    Ford  Focus
1   E432XX77RUS       1  6500.0  Toyota  Camry
2   7184TT36RUS       1  2100.0    Ford  Focus
3  X582HE161RUS       2  2000.0    Ford  Focus
4  92918M178RUS       1  5700.0    Ford  Focus

In [33]:
pd.options.display.float_format = '{:.2f}'.format

In [34]:
sample_cmm = autos[['CarNumber', 'Make', 'Model']].sample(200, random_state=21, replace=True).reset_index(drop=True)

sample_refund = autos['Refund'].sample(n=200, replace=True, random_state=21).reset_index(drop=True)
sample_fines = autos['Fines'].sample(n=200, replace=True, random_state=21).reset_index(drop=True)

concat_rows = pd.concat([autos, sample_cmm, sample_refund, sample_fines])

concat_rows.count()

CarNumber    925
Refund       925
Fines        925
Make         925
Model        914
dtype: int64

In [35]:
np.random.seed(21)

years = pd.Series(np.random.randint(1980, 2019, size=concat_rows.shape[0]), name='Year')
concat_rows['Year'] = years

fines = concat_rows

sn_file_path = './surname.json'
surnames = pd.read_json(sn_file_path)
sn_cols = surnames.loc[0, 0]
sn_rec = surnames.loc[1:, 0]
surnames = pd.Series(sn_rec, name=sn_cols).str.replace(r'[^\w\s]', '', regex=True)

car_numbers = autos['CarNumber'].unique()

np.random.seed(21)
choice_sn = np.random.choice(surnames, len(car_numbers), replace=True)

owners = pd.DataFrame({'CarNumber': car_numbers, 'SURNAME': choice_sn})
owners

FileNotFoundError: File ./surname.json does not exist

In [ ]:
def get_rus_plate():
    letters = ['A','B','E','K','M','H','O','P','C','T','Y','X']
    l1 = np.random.choice(letters)
    num = np.random.randint(100,999)
    l2 = np.random.choice(letters)
    l3 = np.random.choice(letters)
    region = np.random.choice(['77','78','97','99','177','197','799'])
    return f"{l1}{num}{l2}{l3}{region}RUS"

cars = []
for _ in range(5):
    cars.append({
        'CarNumber': get_rus_plate(),
        'Make': np.random.choice(autos['Make']),
        'Model': np.random.choice(autos['Model']),
        'Refund': np.random.uniform(0, 500),
        'Fines': np.random.uniform(0, 1000),
        'Year': np.random.randint(1980, 2020)
    })

cars_df = pd.DataFrame(cars)
fines = pd.concat([fines, cars_df], ignore_index=True)

In [ ]:
owners = owners.iloc[:-20,:].reset_index(drop=True)

randomizer_url = 'https://randomuser.me/api/?results=3'
rand_data = requests.get(randomizer_url).json()

users = []
for i, user in enumerate(rand_data['results']):
    users.append({
        'CarNumber': get_rus_plate(),
        'SURNAME': user['name']['last'].upper()
    })

users_df = pd.DataFrame(users)
pd.concat([owners, users_df], ignore_index=True)

In [ ]:
owners_fines_inner = pd.merge(owners, fines, on='CarNumber', how='inner')
owners_fines_outer = pd.merge(owners, fines, on='CarNumber', how='outer')
owners_fines_right = pd.merge(owners, fines, on='CarNumber', how='right')
owners_fines_left = pd.merge(owners, fines, on='CarNumber', how='left')

In [ ]:
pivot = fines.pivot_table(index=['Make', 'Model'], columns='Year', values='Fines', aggfunc='sum')
print(pivot)

In [ ]:
fines.to_csv('./data/fines.csv', index=False)
owners.to_csv('./data/owners.csv', index=False)

# Exercise 05 : Pandas optimizations

Exercise 05

Pandas optimizations

Turn-in directory : ex05/

Files to turn in : optimizations.ipynb

Allowed functions : import pandas as pd, import gc

We are returning to the idea of code efficiency. By now you know the basics of Pandas.
It is time to get to know some cool stuff that most Pandas users neither use nor know
about.

* read the fines.csv that you saved in the previous exercise
* iterations: in all the following subtasks, you need to calculate `fines/refund*year` for
each row and create a new column with the calculated data and measure the time
using the magic command `%%timeit` in the cell
  * loop: write a function that iterates through the dataframe using `for i in
  range(0, len(df))`, `iloc` and `append()` to a list, assign the result of the function to a new column in the dataframe
  * do it using `iterrows()`
  * do it using `apply()` and lambda function
  * do it using `Series` objects from the dataframe
  * do it as in the previous subtask but with the method `.values`
* indexing: measure the time using the magic command `%%timeit` in the cell
  * get a row for a specific `CarNumber`, for example, `’O136HO197RUS’`
  * set the index in your dataframe with `CarNumber`
  * again, get a row for the same `CarNumber`
* downcasting:
  * run `df.info(memory_usage=’deep’)`, pay attention to the `Dtype` and the memory usage
  * make a `copy()` of your initial dataframe into another dataframe `optimized`
  * downcast from `float64` to `float32` for all the columns
  * downcast from `int64` to the smallest numerical dtype possible
  * run `info(memory_usage='deep')` for your new dataframe, pay attention to the Dtype and the memory usage
* categories:
  * change the `object` type columns to the type `category`
  * This time, check the memory usage, it probably has a decrease of 2–3 times compared to the initial dataframe
* memory clean
  * using `%reset_selective` and the library `gc` clean the memory of your initial dataframe only

In [ ]:
import pandas as pd
import gc

In [ ]:
data_file_path = './data/fines.csv'
df = pd.read_csv(data_file_path)
df

In [ ]:
%%timeit
def calc_loop_fry(df):
    res = []
    for i in range(len(df)):
        fn = df.iloc[i]['Fines']
        rf = df.iloc[i]['Refund']
        year = df.iloc[i]['Year']
        val = fn / rf * year if rf != 0 else None
        res.append(val)
    return res

df['loop_res_fry'] = calc_loop_fry(df)
gc.collect()

In [ ]:
%%timeit
def calc_iterrows_fry(df):
    res = []
    for i, item in df.iterrows():
        fn = item['Fines']
        rf = item['Refund']
        year = item['Year']
        val = fn / rf * year if rf != 0 else None
        res.append(val)
    return res

df['iterrows_res_fry'] = calc_iterrows_fry(df)
gc.collect()

In [ ]:
%%timeit
df['apply_res_fry'] = df.apply(lambda item: item['Fines'] / item['Refund'] * item['Year'] if item['Refund'] != 0 else None, axis=1)
gc.collect()

In [ ]:
%%timeit
df['series_res_fry'] = df['Fines'] / df['Refund'] * df['Year']
gc.collect()

In [ ]:
%%timeit
fn = df['Fines'].values
rf = df['Refund'].values
yr = df['Year'].values
df['values_res_fry'] = fn / rf * yr
gc.collect()

In [ ]:
%%timeit
item = df[df['CarNumber'] == 'O136HO197RUS']

In [ ]:
df_indexed = df.set_index('CarNumber')

In [ ]:
%%timeit
item = df_indexed.loc['O136HO197RUS']

In [ ]:
df.info(memory_usage='deep')

In [ ]:
optimized = df.copy()

In [ ]:
for col in optimized.select_dtypes(include=['float64']).columns:
    optimized[col] = pd.to_numeric(optimized[col], downcast='float')

In [ ]:
for col in optimized.select_dtypes(include=['int64']).columns:
    optimized[col] = pd.to_numeric(optimized[col], downcast='integer')

In [ ]:
optimized.info(memory_usage='deep')

In [ ]:
for col in optimized.select_dtypes(include=['object']).columns:
    optimized[col] = optimized[col].astype('category')

print(optimized.info(memory_usage='deep'))

%reset_selective -f df
gc.collect()