In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("ekibee/car-sales-information")

print("Path to dataset files:", path)

Downloading from https://www.kaggle.com/api/v1/datasets/download/ekibee/car-sales-information?dataset_version_number=14...

100%|██████████| 388M/388M [00:11<00:00, 36.1MB/s]

Extracting files...

Path to dataset files: /root/.cache/kagglehub/datasets/ekibee/car-sales-information/versions/14

In [7]:
import polars as pl

df_link = "/root/.cache/kagglehub/datasets/ekibee/car-sales-information/versions/14/all_regions.csv"

df = pl.read_csv(df_link,
		     encoding='utf8',
		     dtypes={'engineDisplacement': str})

df.head()

<ipython-input-7-2e9bd8c18394>:5: DeprecationWarning: The argument `dtypes` for `read_csv` is deprecated. It has been renamed to `schema_overrides`.
  df = pl.read_csv(df_link,

shape: (5, 18)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ brand     ┆ name      ┆ bodyType  ┆ color     ┆ … ┆ location  ┆ link      ┆ descripti ┆ parse_da │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ on        ┆ te       │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ str       ┆ str       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Volkswage ┆ Golf      ┆ Хэтчбек 5 ┆ Серебрист ┆ … ┆ Майкоп    ┆ https://m ┆ 101 л.с.  ┆ 2023-05- │
│ n         ┆           ┆ дв.       ┆ ый        ┆   ┆           ┆ aykop.dro ┆ люк не    ┆ 02       │
│           ┆           ┆           ┆           ┆   ┆           ┆ m.ru/volk ┆ течёт.    ┆ 01:00:00 │
│           ┆           ┆           ┆           ┆   ┆           ┆ swa…      ┆ Докумен…  ┆          │
│ Лада      ┆ 1111 Ока  ┆ Хэтчбек 3 ┆ Фиолетовы ┆ … ┆ Майкоп    ┆ https://m ┆ Ваз Ока   ┆ 2023-05- │
│           ┆           ┆ дв.       ┆ й         ┆   ┆           ┆ aykop.dro ┆ Год: 2003 ┆ 02       │
│           ┆           ┆           ┆           ┆   ┆           ┆ m.ru/lada ┆ Цвет:     ┆ 20:00:00 │
│           ┆           ┆           ┆           ┆   ┆           ┆ /ok…      ┆ Баклаж…   ┆          │
│ Toyota    ┆ Funcargo  ┆ Хэтчбек 5 ┆ Серебрист ┆ … ┆ Майкоп    ┆ https://m ┆ ХОРОШЕЕ   ┆ 2023-05- │
│           ┆           ┆ дв.       ┆ ый        ┆   ┆           ┆ aykop.dro ┆ СОСТОЯНИЕ ┆ 02       │
│           ┆           ┆           ┆           ┆   ┆           ┆ m.ru/toyo ┆ . замена  ┆ 20:00:00 │
│           ┆           ┆           ┆           ┆   ┆           ┆ ta/…      ┆ комп…     ┆          │
│ Лада      ┆ Гранта    ┆ Лифтбек   ┆ Серый     ┆ … ┆ Майкоп    ┆ https://m ┆ Автомобил ┆ 2023-05- │
│           ┆           ┆           ┆           ┆   ┆           ┆ aykop.dro ┆ ь в       ┆ 02       │
│           ┆           ┆           ┆           ┆   ┆           ┆ m.ru/lada ┆ отличном  ┆ 23:00:00 │
│           ┆           ┆           ┆           ┆   ┆           ┆ /gr…      ┆ техничес… ┆          │
│ Лада      ┆ Нива      ┆ Джип 3    ┆ Зеленый   ┆ … ┆ Яблоновск ┆ https://y ┆ Модель:   ┆ 2023-05- │
│           ┆ Легенд    ┆ дв.       ┆           ┆   ┆ ий        ┆ ablonovsk ┆ Нива      ┆ 02       │
│           ┆           ┆           ┆           ┆   ┆           ┆ iy.drom.r ┆ Легенд    ┆ 20:00:00 │
│           ┆           ┆           ┆           ┆   ┆           ┆ u/l…      ┆ Комплекта ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ ц…        ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [8]:
df[15, :]

shape: (1, 18)
┌─────────┬───────┬────────────┬───────┬───┬─────────────┬─────────────┬─────────────┬─────────────┐
│ brand   ┆ name  ┆ bodyType   ┆ color ┆ … ┆ location    ┆ link        ┆ description ┆ parse_date  │
│ ---     ┆ ---   ┆ ---        ┆ ---   ┆   ┆ ---         ┆ ---         ┆ ---         ┆ ---         │
│ str     ┆ str   ┆ str        ┆ str   ┆   ┆ str         ┆ str         ┆ str         ┆ str         │
╞═════════╪═══════╪════════════╪═══════╪═══╪═════════════╪═════════════╪═════════════╪═════════════╡
│ Hyundai ┆ Creta ┆ Джип 5 дв. ┆ Серый ┆ … ┆ Яблоновский ┆ https://yab ┆ Машина в    ┆ 2023-05-02  │
│         ┆       ┆            ┆       ┆   ┆             ┆ lonovskiy.d ┆ хорошем     ┆ 03:00:00    │
│         ┆       ┆            ┆       ┆   ┆             ┆ rom.ru/h…   ┆ состоянии   ┆             │
│         ┆       ┆            ┆       ┆   ┆             ┆             ┆ ТО …        ┆             │
└─────────┴───────┴────────────┴───────┴───┴─────────────┴─────────────┴─────────────┴─────────────┘

In [10]:
df[10:15, :]

shape: (5, 18)
┌───────┬────────┬─────────────┬────────┬───┬─────────────┬─────────────┬─────────────┬────────────┐
│ brand ┆ name   ┆ bodyType    ┆ color  ┆ … ┆ location    ┆ link        ┆ description ┆ parse_date │
│ ---   ┆ ---    ┆ ---         ┆ ---    ┆   ┆ ---         ┆ ---         ┆ ---         ┆ ---        │
│ str   ┆ str    ┆ str         ┆ str    ┆   ┆ str         ┆ str         ┆ str         ┆ str        │
╞═══════╪════════╪═════════════╪════════╪═══╪═════════════╪═════════════╪═════════════╪════════════╡
│ Audi  ┆ A8     ┆ Седан       ┆ Черный ┆ … ┆ Майкоп      ┆ https://may ┆ без пробега ┆ 2023-05-02 │
│       ┆        ┆             ┆        ┆   ┆             ┆ kop.drom.ru ┆ по РФ в     ┆ 00:00:00   │
│       ┆        ┆             ┆        ┆   ┆             ┆ /audi/a8…   ┆ отличном с… ┆            │
│ Лада  ┆ Гранта ┆ Седан       ┆ Белый  ┆ … ┆ Яблоновский ┆ https://yab ┆ Модель:     ┆ 2023-05-02 │
│       ┆        ┆             ┆        ┆   ┆             ┆ lonovskiy.d ┆ Гранта Комп ┆ 00:00:00   │
│       ┆        ┆             ┆        ┆   ┆             ┆ rom.ru/l…   ┆ лектация:   ┆            │
│       ┆        ┆             ┆        ┆   ┆             ┆             ┆ L…          ┆            │
│ Лада  ┆ 2114   ┆ Хэтчбек 5   ┆ Черный ┆ … ┆ Майкоп      ┆ https://may ┆ в хорошем   ┆ 2023-05-03 │
│       ┆ Самара ┆ дв.         ┆        ┆   ┆             ┆ kop.drom.ru ┆ состоянии.г ┆ 06:00:00   │
│       ┆        ┆             ┆        ┆   ┆             ┆ /lada/21…   ┆ нили нет,…  ┆            │
│ Лада  ┆ Гранта ┆ Седан       ┆ Белый  ┆ … ┆ Яблоновский ┆ https://yab ┆ Модель:     ┆ 2023-05-02 │
│       ┆        ┆             ┆        ┆   ┆             ┆ lonovskiy.d ┆ Гранта Комп ┆ 00:00:00   │
│       ┆        ┆             ┆        ┆   ┆             ┆ rom.ru/l…   ┆ лектация:   ┆            │
│       ┆        ┆             ┆        ┆   ┆             ┆             ┆ L…          ┆            │
│ Лада  ┆ Гранта ┆ Седан       ┆ Белый  ┆ … ┆ Яблоновский ┆ https://yab ┆ Модель:     ┆ 2023-05-02 │
│       ┆        ┆             ┆        ┆   ┆             ┆ lonovskiy.d ┆ Гранта Комп ┆ 00:00:00   │
│       ┆        ┆             ┆        ┆   ┆             ┆ rom.ru/l…   ┆ лектация:   ┆            │
│       ┆        ┆             ┆        ┆   ┆             ┆             ┆ L…          ┆            │
└───────┴────────┴─────────────┴────────┴───┴─────────────┴─────────────┴─────────────┴────────────┘

In [11]:
df.select(['brand', 'color', 'mileage', 'price']).head(5)

shape: (5, 4)
┌────────────┬─────────────┬──────────┬─────────┐
│ brand      ┆ color       ┆ mileage  ┆ price   │
│ ---        ┆ ---         ┆ ---      ┆ ---     │
│ str        ┆ str         ┆ f64      ┆ i64     │
╞════════════╪═════════════╪══════════╪═════════╡
│ Volkswagen ┆ Серебристый ┆ 240000.0 ┆ 280000  │
│ Лада       ┆ Фиолетовый  ┆ 37000.0  ┆ 95000   │
│ Toyota     ┆ Серебристый ┆ 295000.0 ┆ 380000  │
│ Лада       ┆ Серый       ┆ 16000.0  ┆ 795000  │
│ Лада       ┆ Зеленый     ┆ null     ┆ 1022900 │
└────────────┴─────────────┴──────────┴─────────┘

In [13]:
df.select([
    pl.col('price').max().alias('price_max'),
    pl.col('brand').n_unique().alias('brand_names_count'),
    pl.col('mileage').min().alias('mileage_min')
])

shape: (1_294_757, 3)
┌───────────┬───────────────────┬─────────────┐
│ price_max ┆ brand_names_count ┆ mileage_min │
│ ---       ┆ ---               ┆ ---         │
│ i64       ┆ str               ┆ f64         │
╞═══════════╪═══════════════════╪═════════════╡
│ 150000000 ┆ Volkswagen        ┆ 1000.0      │
│ 150000000 ┆ Лада              ┆ 1000.0      │
│ 150000000 ┆ Toyota            ┆ 1000.0      │
│ 150000000 ┆ Лада              ┆ 1000.0      │
│ 150000000 ┆ Лада              ┆ 1000.0      │
│ …         ┆ …                 ┆ …           │
│ 150000000 ┆ BMW               ┆ 1000.0      │
│ 150000000 ┆ Лада              ┆ 1000.0      │
│ 150000000 ┆ Toyota            ┆ 1000.0      │
│ 150000000 ┆ Лада              ┆ 1000.0      │
│ 150000000 ┆ Лада              ┆ 1000.0      │
└───────────┴───────────────────┴─────────────┘

In [17]:
df.filter((pl.col("brand") == "Toyota")
          & (pl.col("color") == "Черный")
          & (pl.col('year') > 2015) ).sort("price").limit(3)

shape: (3, 18)
┌────────┬───────┬──────────────┬────────┬───┬──────────┬──────────────┬─────────────┬─────────────┐
│ brand  ┆ name  ┆ bodyType     ┆ color  ┆ … ┆ location ┆ link         ┆ description ┆ parse_date  │
│ ---    ┆ ---   ┆ ---          ┆ ---    ┆   ┆ ---      ┆ ---          ┆ ---         ┆ ---         │
│ str    ┆ str   ┆ str          ┆ str    ┆   ┆ str      ┆ str          ┆ str         ┆ str         │
╞════════╪═══════╪══════════════╪════════╪═══╪══════════╪══════════════╪═════════════╪═════════════╡
│ Toyota ┆ Passo ┆ Хэтчбек 5    ┆ Черный ┆ … ┆ Якутск   ┆ https://yaku ┆ Состояние   ┆ 2023-06-03  │
│        ┆       ┆ дв.          ┆        ┆   ┆          ┆ tsk.drom.ru/ ┆ отличное    ┆ 08:00:00    │
│        ┆       ┆              ┆        ┆   ┆          ┆ toyota…      ┆ без         ┆             │
│        ┆       ┆              ┆        ┆   ┆          ┆              ┆ вложени…    ┆             │
│ Toyota ┆ Passo ┆ Хэтчбек 5    ┆ Черный ┆ … ┆ Улан-Удэ ┆ https://ulan ┆ 25ПТС. 1    ┆ 2023-05-27  │
│        ┆       ┆ дв.          ┆        ┆   ┆          ┆ -ude.drom.ru ┆ хозяин. В   ┆ 21:00:00    │
│        ┆       ┆              ┆        ┆   ┆          ┆ /toyot…      ┆ родном      ┆             │
│        ┆       ┆              ┆        ┆   ┆          ┆              ┆ окра…       ┆             │
│ Toyota ┆ Passo ┆ Хэтчбек 5    ┆ Черный ┆ … ┆ Якутск   ┆ https://yaku ┆ В эти дни   ┆ 2023-06-08  │
│        ┆       ┆ дв.          ┆        ┆   ┆          ┆ tsk.drom.ru/ ┆ 9-10-11.06. ┆ 20:00:00    │
│        ┆       ┆              ┆        ┆   ┆          ┆ toyota…      ┆ 23г. сумм…  ┆             │
└────────┴───────┴──────────────┴────────┴───┴──────────┴──────────────┴─────────────┴─────────────┘

In [18]:
q = (
    df.lazy()
    .drop_nulls()
    .filter(
        (pl.col('brand') == 'Mercedes-Benz')
        & (pl.col('color') == 'Черный')
        & (pl.col('bodyType') == 'Седан')
        & (pl.col('year') > 2010))
    .sort(['year', 'price'])
    .limit(5)
)
%time q.collect()

CPU times: user 70.3 ms, sys: 1.97 ms, total: 72.2 ms
Wall time: 66.6 ms

shape: (5, 18)
┌────────────┬─────────┬──────────┬────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ brand      ┆ name    ┆ bodyType ┆ color  ┆ … ┆ location   ┆ link       ┆ descriptio ┆ parse_date │
│ ---        ┆ ---     ┆ ---      ┆ ---    ┆   ┆ ---        ┆ ---        ┆ n          ┆ ---        │
│ str        ┆ str     ┆ str      ┆ str    ┆   ┆ str        ┆ str        ┆ ---        ┆ str        │
│            ┆         ┆          ┆        ┆   ┆            ┆            ┆ str        ┆            │
╞════════════╪═════════╪══════════╪════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ Mercedes-B ┆ C-Class ┆ Седан    ┆ Черный ┆ … ┆ Москва     ┆ https://mo ┆ По запросу ┆ 2023-06-01 │
│ enz        ┆         ┆          ┆        ┆   ┆            ┆ scow.drom. ┆ отправим   ┆ 20:00:00   │
│            ┆         ┆          ┆        ┆   ┆            ┆ ru/mercede ┆ VIN и      ┆            │
│            ┆         ┆          ┆        ┆   ┆            ┆ …          ┆ виде…      ┆            │
│ Mercedes-B ┆ C-Class ┆ Седан    ┆ Черный ┆ … ┆ Москва     ┆ https://mo ┆ По запросу ┆ 2023-05-24 │
│ enz        ┆         ┆          ┆        ┆   ┆            ┆ scow.drom. ┆ отправим   ┆ 03:00:00   │
│            ┆         ┆          ┆        ┆   ┆            ┆ ru/mercede ┆ VIN и      ┆            │
│            ┆         ┆          ┆        ┆   ┆            ┆ …          ┆ виде…      ┆            │
│ Mercedes-B ┆ E-Class ┆ Седан    ┆ Черный ┆ … ┆ Красноярск ┆ https://kr ┆ не заводит ┆ 2023-05-11 │
│ enz        ┆         ┆          ┆        ┆   ┆            ┆ asnoyarsk. ┆ ься,       ┆ 01:00:00   │
│            ┆         ┆          ┆        ┆   ┆            ┆ drom.ru/me ┆ срочно     ┆            │
│            ┆         ┆          ┆        ┆   ┆            ┆ …          ┆            ┆            │
│ Mercedes-B ┆ E-Class ┆ Седан    ┆ Черный ┆ … ┆ Омск       ┆ https://om ┆ После      ┆ 2023-06-02 │
│ enz        ┆         ┆          ┆        ┆   ┆            ┆ sk.drom.ru ┆ ДТП,вся    ┆ 18:00:00   │
│            ┆         ┆          ┆        ┆   ┆            ┆ /mercedes- ┆ безопаснос ┆            │
│            ┆         ┆          ┆        ┆   ┆            ┆ …          ┆ ть на …    ┆            │
│ Mercedes-B ┆ E-Class ┆ Седан    ┆ Черный ┆ … ┆ Ангарск    ┆ https://an ┆ Без        ┆ 2023-06-01 │
│ enz        ┆         ┆          ┆        ┆   ┆            ┆ garsk.drom ┆ торга.Все  ┆ 01:00:00   │
│            ┆         ┆          ┆        ┆   ┆            ┆ .ru/merced ┆ вопросы по ┆            │
│            ┆         ┆          ┆        ┆   ┆            ┆ …          ┆ тел. …     ┆            │
└────────────┴─────────┴──────────┴────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [19]:
lazy_df_pl = pl.scan_csv(df_link,
			   encoding='utf8',
			   dtypes={'engineDisplacement': str})
lazy_df_pl

<ipython-input-19-ef13fb6259b6>:1: DeprecationWarning: The argument `dtypes` for `scan_csv` is deprecated. It has been renamed to `schema_overrides`.
  lazy_df_pl = pl.scan_csv(df_link,

In [20]:
lazy_df_pl.fetch(5)

<ipython-input-20-d2588b925bb3>:1: DeprecationWarning: `LazyFrame.fetch` is deprecated. `LazyFrame.fetch` is deprecated; use `LazyFrame.collect` instead, in conjunction with a call to `head`.
  lazy_df_pl.fetch(5)

shape: (5, 18)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ brand     ┆ name      ┆ bodyType  ┆ color     ┆ … ┆ location  ┆ link      ┆ descripti ┆ parse_da │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ on        ┆ te       │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ str       ┆ str       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Volkswage ┆ Golf      ┆ Хэтчбек 5 ┆ Серебрист ┆ … ┆ Майкоп    ┆ https://m ┆ 101 л.с.  ┆ 2023-05- │
│ n         ┆           ┆ дв.       ┆ ый        ┆   ┆           ┆ aykop.dro ┆ люк не    ┆ 02       │
│           ┆           ┆           ┆           ┆   ┆           ┆ m.ru/volk ┆ течёт.    ┆ 01:00:00 │
│           ┆           ┆           ┆           ┆   ┆           ┆ swa…      ┆ Докумен…  ┆          │
│ Лада      ┆ 1111 Ока  ┆ Хэтчбек 3 ┆ Фиолетовы ┆ … ┆ Майкоп    ┆ https://m ┆ Ваз Ока   ┆ 2023-05- │
│           ┆           ┆ дв.       ┆ й         ┆   ┆           ┆ aykop.dro ┆ Год: 2003 ┆ 02       │
│           ┆           ┆           ┆           ┆   ┆           ┆ m.ru/lada ┆ Цвет:     ┆ 20:00:00 │
│           ┆           ┆           ┆           ┆   ┆           ┆ /ok…      ┆ Баклаж…   ┆          │
│ Toyota    ┆ Funcargo  ┆ Хэтчбек 5 ┆ Серебрист ┆ … ┆ Майкоп    ┆ https://m ┆ ХОРОШЕЕ   ┆ 2023-05- │
│           ┆           ┆ дв.       ┆ ый        ┆   ┆           ┆ aykop.dro ┆ СОСТОЯНИЕ ┆ 02       │
│           ┆           ┆           ┆           ┆   ┆           ┆ m.ru/toyo ┆ . замена  ┆ 20:00:00 │
│           ┆           ┆           ┆           ┆   ┆           ┆ ta/…      ┆ комп…     ┆          │
│ Лада      ┆ Гранта    ┆ Лифтбек   ┆ Серый     ┆ … ┆ Майкоп    ┆ https://m ┆ Автомобил ┆ 2023-05- │
│           ┆           ┆           ┆           ┆   ┆           ┆ aykop.dro ┆ ь в       ┆ 02       │
│           ┆           ┆           ┆           ┆   ┆           ┆ m.ru/lada ┆ отличном  ┆ 23:00:00 │
│           ┆           ┆           ┆           ┆   ┆           ┆ /gr…      ┆ техничес… ┆          │
│ Лада      ┆ Нива      ┆ Джип 3    ┆ Зеленый   ┆ … ┆ Яблоновск ┆ https://y ┆ Модель:   ┆ 2023-05- │
│           ┆ Легенд    ┆ дв.       ┆           ┆   ┆ ий        ┆ ablonovsk ┆ Нива      ┆ 02       │
│           ┆           ┆           ┆           ┆   ┆           ┆ iy.drom.r ┆ Легенд    ┆ 20:00:00 │
│           ┆           ┆           ┆           ┆   ┆           ┆ u/l…      ┆ Комплекта ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ ц…        ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘